In [5]:
#TO GET MORE FUNCTIONALLITY ,FAST CALCULATION ,MATHEMATICAL EXPRESSION WE SHOULD USE NUMPY NOT LIST
#array function always take list and touple
import numpy as np
l1=[1,2,3,4]
l2=[5,6,7,8]
sum_list=[i+j for i,j in zip(l1,l2)]
print sum_list
arr1=np.array(l1)
arr2=np.array(l2)
sum_array=arr1+arr2
print sum_array

[6, 8, 10, 12]
[ 6  8 10 12]


In [10]:
li=[1,"srikant",5.76,3+4j]#list can contain any type of data
arr=np.array(range(10))#numpy array contain only homogenious data
arr1=np.array((23,34,45))#it will convert touple into array
arr1[0]=13.8#it shows that nummy is mutable
print arr1,type(arr1)
arr1.dtype


[13 34 45] <type 'numpy.ndarray'>


dtype('int32')

In [14]:
np.array([1,2,'3','4']) #it will convert all data to string

array(['1', '2', '3', '4'], dtype='|S11')

In [16]:
np.array([1,2,3,4,5.6])#convert all int to float

array([1. , 2. , 3. , 4. , 5.6])

In [17]:
np.array([1,2,3,6.4,7.4],dtype=int)#by this you can mention this data type

array([1, 2, 3, 6, 7])

In [2]:
#OPERATION OF NUMPY ARRAY FROM LIST AND TOUPLE
import numpy as np
arr=np.array(range(10))
print arr
print arr.size #total size of array
print arr.ndim #dimention of array
print "number of row and collumn",arr.shape #number of row and collumn
print arr.itemsize #how much memory occupied for one element in array(here 4 bytes)
print arr.size*arr.itemsize#total memory is occupied by array
arr.reshape(2,5)#converting array into 2 row and 5 collumn(as 10 is size(2*5))


[0 1 2 3 4 5 6 7 8 9]
10
1
number of row and collumn (10,)
4
40


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
#operation on array
#this operation will work only size of both array should same we must check that
#if datatype diff see next
arr1=np.array(range(10,20))
arr2=np.array(range(20,30))
print arr1+arr2
print arr1*arr2
print arr1-arr2
print arr1/arr2
print 2*arr1

[30 32 34 36 38 40 42 44 46 48]
[200 231 264 299 336 375 416 459 504 551]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[0 0 0 0 0 0 0 0 0 0]
[20 22 24 26 28 30 32 34 36 38]


In [38]:
#size are not same that why it is not working
arr1=np.array(range(6))
arr2=np.array(range(8))
print arr1
print arr2
print arr1+arr2

[0 1 2 3 4 5]
[0 1 2 3 4 5 6 7]


ValueError: operands could not be broadcast together with shapes (6,) (8,) 

In [39]:
print np.arange(0,1,.1)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [42]:
np.array(range(10),dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
#use diff linspace like arrange 
np.linspace(0,2,9)#arg=staring,ending,number of element you want

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [45]:
np.linspace(0,2,9).reshape(3,3)

array([[0.  , 0.25, 0.5 ],
       [0.75, 1.  , 1.25],
       [1.5 , 1.75, 2.  ]])

In [47]:
#to get random list
np.random.random((2,4)) #mentioning the size in touple

array([[0.76318468, 0.87945971, 0.77604903, 0.81729962],
       [0.7659431 , 0.50393385, 0.70278071, 0.10474543]])

In [50]:
#size same and diff data type(int,float),mathematical operation possible
arr1=np.array(range(10),dtype="int")
arr2=np.array(range(10),dtype="float")
print arr1
print arr2
arr1+arr2

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [51]:
#size same and diff data type(int,string),mathematical operation possible
arr1=np.array(range(10),dtype="int")
arr2=np.array(range(10),dtype="str")
print arr1
print arr2
arr1+arr2

[0 1 2 3 4 5 6 7 8 9]
['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']


TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('S11') dtype('S11') dtype('S11')

In [60]:
10+30.5 #it is possible
#40+"gjh" #it is not
"fgf"+"mbmg"

'fgfmbmg'

In [65]:
#slicing .difference between list sliceing and numpy arr slicing
arr=np.array(range(10))
l=range(10)
l1=l[0:3] #here l1 is diiferent object
l1[1]=50
arr1=arr[0:3]#here arr1 in point to arr means same object
arr1[1]=50
print l
print arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0 50  2  3  4  5  6  7  8  9]


In [78]:
arr=np.arange(15).reshape(3,5)
print arr
print "sum of all",arr.sum()
print "sum of every collumn",arr.sum(axis=0)#add of row
print "sum of every row",arr.sum(axis=1)#addition of collumn
print "max of every row",arr.max(axis=1)
print "max of every collumn",arr.max(axis=0)
arr.min()

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
sum of all 105
sum of every collumn [15 18 21 24 27]
sum of every row [10 35 60]
max of every row [ 4  9 14]
max of every collumn [10 11 12 13 14]


0

In [86]:
l=[1,2,3,4,5]
l2=l[:]#copy to new object
print l1,id(l)
print l2,id(l2)
arr=np.arange(10,20)
arr1=arr.copy()#copy to new array object
print arr1,id(arr1)
print arr,id(arr)

[0, 50, 2] 2964063148
[1, 2, 3, 4, 5] 2964739116
[10 11 12 13 14 15 16 17 18 19] 2964079904
[10 11 12 13 14 15 16 17 18 19] 2964078824


In [148]:
arr=np.arange(1,10).reshape(3,3)
print arr
arr[:2,:2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2],
       [4, 5]])

In [105]:
#confusion T and transpose behaviuor
arr=np.arange(1,10).reshape(3,3)
arr1=arr.T
arr2=arr.transpose()
print arr,id(arr)
print "transpose of array"
print arr1,id(arr1)
print "tranpose by transpose function"
print arr2,id(arr2)
arr2[0][1]=100
arr

[[1 2 3]
 [4 5 6]
 [7 8 9]] 2964133072
transpose of array
[[1 4 7]
 [2 5 8]
 [3 6 9]] 2964135632
tranpose by transpose function
[[1 4 7]
 [2 5 8]
 [3 6 9]] 2964133392


array([[  1,   2,   3],
       [100,   5,   6],
       [  7,   8,   9]])

In [116]:
#if any one element is false it will return false(all function)
arr=np.arange(10)
print arr
print arr.all()#bool(0)=false
print np.arange(1,10).all()

[0 1 2 3 4 5 6 7 8 9]
False
True


In [117]:
#any function is opposite of all function
arr=np.arange(10)
print arr
print arr.any()#bool(0)=false
print np.arange(1,10).any()

[0 1 2 3 4 5 6 7 8 9]
True
True


In [122]:
#argsmax give index of max number of array
arr=np.array([65,77,67,89,78,54])
print arr.argmax()
print arr.argmin()
print arr.reshape(2,3)
print arr.reshape(2,3).argmax(axis=0)

3
5
[[65 77 67]
 [89 78 54]]
[1 1 0]


In [123]:
#astype is used change datatype
arr=np.array([65,77,67,89,78,54])
print arr.astype("complex")

[65.+0.j 77.+0.j 67.+0.j 89.+0.j 78.+0.j 54.+0.j]


In [ ]:
#partition function

In [129]:
#checking the base of sub array

arr=np.array(range(10))
x=arr[3:6]
print x
print x.base
print x.base is arr

[3 4 5]
[0 1 2 3 4 5 6 7 8 9]
True


In [130]:
#diagonal function

In [138]:
#flat and flattern multidimentional to single dimention array
arr=arr=np.array(range(10)).reshape(5,2)
print arr
print arr.flatten()
print arr.flat

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [153]:
#vstack used to vertical merege 
arr1=np.array(range(10,20)).reshape(2,5)
arr2=np.array(range(20,30)).reshape(2,5)
print "arr1=",arr1
print "arr2=",arr2

print "vertical merge",np.vstack((arr1,arr2))
print "horizontal merge",np.hstack((arr1,arr2))


arr1= [[10 11 12 13 14]
 [15 16 17 18 19]]
arr2= [[20 21 22 23 24]
 [25 26 27 28 29]]
vertical merge [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
horizontal merge [[10 11 12 13 14 20 21 22 23 24]
 [15 16 17 18 19 25 26 27 28 29]]
