In [2]:
import numpy as np
import cv2
img=cv2.imread("jack.jpg")
cv2.namedWindow("image",cv2.WINDOW_NORMAL)
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite("output.png",img)#size will be differrent from main jpg

True

In [28]:
import numpy as np
import cv2
img=cv2.imread("jack.jpg",1)#1 because same imagecolor will be passing/bydefault its 1 not mendatory

print img
print "dimention of array",img.ndim
print "type of image",type(img)
print "number of row",len(img)#number of row
print "total value in top row",len(img[0])#total value in top row/vertical collumns
print "num of channel first row",len(img[0][0])#num of channel(rgb)
print "no of(row,collumn,channel)of image=",img.shape
print img.dtype#uint8(unsigned integer of 8)max each px->0-2**8/256
print img[10,5]#pixel value of that array
print "one channel image",img[:,:,0]#print 1st channel image
print "total size",img.size


[[[ 46  35   3]
  [ 64  51  19]
  [ 60  45  13]
  ...
  [ 69  47  19]
  [ 71  44  23]
  [ 68  41  21]]

 [[ 49  38   6]
  [ 59  48  16]
  [ 57  42  10]
  ...
  [ 71  49  21]
  [ 67  40  19]
  [ 63  36  16]]

 [[ 52  43  10]
  [ 55  44  12]
  [ 52  39   7]
  ...
  [ 73  51  23]
  [ 72  45  24]
  [ 74  47  27]]

 ...

 [[ 21  23  33]
  [ 20  22  32]
  [ 23  25  35]
  ...
  [110 101  88]
  [140 123 110]
  [173 154 141]]

 [[ 21  23  33]
  [ 24  26  36]
  [ 22  24  34]
  ...
  [141 127 115]
  [166 144 132]
  [185 159 145]]

 [[ 15  17  27]
  [ 24  26  36]
  [ 23  25  35]
  ...
  [163 147 134]
  [186 160 148]
  [194 165 151]]]
dimention of array 3
type of image <type 'numpy.ndarray'>
number of row 800
total value in top row 1280
num of channel first row 3
no of(row,collumn,channel)of image= (800, 1280, 3)
uint8
[67 46 15]
one channel image [[ 46  64  60 ...  69  71  68]
 [ 49  59  57 ...  71  67  63]
 [ 52  55  52 ...  73  72  74]
 ...
 [ 21  20  23 ... 110 140 173]
 [ 21  24  22 ... 141 16

In [7]:
import numpy as np
import cv2

black=np.zeros([150,200,1],'uint8')
#print black
cv2.imshow("black",black)
print(black[0,0,:])#print all bgr value of of that pixel(0,0) location

ones=np.ones([150,200,3],'uint8')
#ones *=(2**8-1) convert to 255,255,255 array to get white value
cv2.imshow("ones",ones)
print(ones[0,0,:])#print all bgr value of of that pixel(0,0) location
#above to images color of image of almost same or same pixel 0,1 alomost same

white=np.ones([150,200,3],'uint16')#array of ones
white *=(2**16-1)#by maltiply max value changing array to max pixel value
cv2.imshow("white",white)#maximun size of 16 bit image
print(white[0,0,:])#print all bgr value of of that pixel(0,0) location

color=ones.copy()
#print color
color[:,:]=(255,0,0)
cv2.imshow("blue",color)
print color[0,0,:]

cv2.waitKey(0)
cv2.destroyAllWindows()

[0]
[1 1 1]
[65535 65535 65535]
[255   0   0]
